---
- hosts: all
  become: true
  tasks:
    - name: install web components
      yum: name={{item}} state=present update_cache=yes
      with_items:
        - docker

    - name: ensure docker started
      service: name=docker state=started enabled=yes

    - name: copy website source code to server
      copy: src=../website/ dest=/tmp/website/ mode=0755

    - name: copy dockerfile to server
      copy: src=docker-webserver-build/Dockerfile dest=/tmp mode=0755

    - name: build the website docker image
      shell: docker build -t vibrato/website .
      args:
        chdir: /tmp/

    - name: Downloaded docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose;chmod +x /usr/local/bin/docker-compose;

    - name: copy docker-compose file stack.yml to server
      copy: src=docker-compose/stack.yml dest=/tmp/ mode=0755
